# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\connect.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(374, 422)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 40, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 140, 47, 13))
        self.label_3.setObjectName("label_3")
        self.hostTextEdit = QtWidgets.QTextEdit(Form)
        self.hostTextEdit.setGeometry(QtCore.QRect(130, 30, 181, 31))
        self.hostTextEdit.setObjectName("hostTextEdit")
        self.portTextEdit = QtWidgets.QTextEdit(Form)
        self.portTextEdit.setGeometry(QtCore.QRect(130, 80, 181, 31))
        self.portTextEdit.setObjectName("portTextEdit")
        self.nameTextEdit = QtWidgets.QTextEdit(Form)
        self.nameTextEdit.setGeometry(QtCore.QRect(130, 130, 181, 31))
        self.nameTextEdit.setObjectName("nameTextEdit")
        self.connectButton = QtWidgets.QPushButton(Form)
        self.connectButton.setGeometry(QtCore.QRect(140, 300, 91, 51))
        self.connectButton.setObjectName("connectButton")
        self.emailTextEdit = QtWidgets.QTextEdit(Form)
        self.emailTextEdit.setGeometry(QtCore.QRect(130, 180, 181, 31))
        self.emailTextEdit.setObjectName("emailTextEdit")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 190, 47, 13))
        self.label_4.setObjectName("label_4")
        self.localTextEdit = QtWidgets.QTextEdit(Form)
        self.localTextEdit.setGeometry(QtCore.QRect(130, 230, 181, 31))
        self.localTextEdit.setObjectName("localTextEdit")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(40, 240, 47, 13))
        self.label_5.setObjectName("label_5")
        self.verifyLabel = QtWidgets.QLabel(Form)
        self.verifyLabel.setGeometry(QtCore.QRect(140, 376, 91, 20))
        self.verifyLabel.setObjectName("verifyLabel")
        self.verifyLabel.setVisible(False)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "HostName"))
        self.label_2.setText(_translate("Form", "Port"))
        self.label_3.setText(_translate("Form", "Nome"))
        self.connectButton.setText(_translate("Form", "Connect"))
        self.label_4.setText(_translate("Form", "Email"))
        self.label_5.setText(_translate("Form", "Local"))
        self.verifyLabel.setText(_translate("Form", "Verificando email..."))
